# https://github.com/openai/codex/blob/main/docs/config.md

model_provider = "openrouter"
model = "openai/gpt-5.2"
# model = "openai/gpt-5.1-codex"
model_reasoning_effort = "high"
disable_response_storage = true
approval_policy = "on-request"

[model_providers.openrouter]
name = "OpenRouter"
base_url = "https://openrouter.ai/api/v1"
# wire_api = "responses"
env_key = "CODEX_OPENROUTER_API_KEY"

[features]
web_search_request = true

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"
enabled = false
