# https://docs.litellm.ai/docs/tutorials/claude_responses_api
# https://docs.anthropic.com/en/docs/claude-code/llm-gateway
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

model_list:
  - model_name: claude-opus-*
    litellm_params:
      model: anthropic/hf:moonshotai/Kimi-K2.5
      api_base: https://api.synthetic.new/anthropic
      api_key: os.environ/SYNTHETIC_API_KEY

  - model_name: claude-sonnet-*
    litellm_params:
      model: anthropic/hf:moonshotai/Kimi-K2.5
      api_base: https://api.synthetic.new/anthropic
      api_key: os.environ/SYNTHETIC_API_KEY

  - model_name: claude-haiku-*
    litellm_params:
      model: anthropic/glm-4.7
      api_base: https://api.z.ai/api/anthropic
      api_key: os.environ/ZAI_API_KEY

  - model_name: "synthetic/*"
    litellm_params:
      model: "anthropic/*"
      api_base: https://api.synthetic.new/anthropic
      api_key: os.environ/SYNTHETIC_API_KEY

  - model_name: "zai/*"
    litellm_params:
      model: "anthropic/*"
      api_base: https://api.z.ai/api/anthropic
      api_key: os.environ/ZAI_API_KEY
