"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# format = """
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status"""

format = """
$git_state\
$git_metrics\
$git_status"""

[git_branch]
symbol = " "
format = '[$branch(:$remote_branch)]($style) '
truncation_length = 4
style = "purple"

[git_status]
untracked = '[?$count](blue) '
staged = '[++$count](green) '
stashed = ""
deleted = '[D$count](red) '
modified = '[M$count](yellow) '
renamed = '[R$count](136) '
conflicted = '[!$count](red) '
behind = '[⇣${count}](purple) '
ahead = '[⇡${count}](purple) '
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](purple) '
format = '([$all_status$ahead_behind]($style))'
style = 'red'

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

[git_state]
style = "yellow"

[git_commit]
commit_hash_length = 4
style = "green"

[directory]
read_only = " 󰌾"
style = "cyan"
